steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/gcr-testing-258008/models:1.0', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gcr-testing-258008/models:1.0']
